# database.py
# ------------------------------------------------------------
# ⚠️  STUB FILE — Owned by Person A (Backend Developer)
# Person B: DO NOT edit this file
# These functions will be implemented by Person A
# ------------------------------------------------------------

def add_item(name, quantity, purchase_date, expiry_date, category):
    """Add a new item to the pantry database"""
    pass  # Person A will implement this

def get_all_items():
    """Return all pantry items as a list of dicts"""
    return []  # Person A will implement this

def get_expiring_items(days=7):
    """Return items expiring within 'days' number of days"""
    return []  # Person A will implement this

def delete_item(item_id):
    """Delete an item by its ID"""
    pass  # Person A will implement this

def update_item(item_id, **kwargs):
    """Update item fields by item ID"""
    pass  # Person A will implement this