# notifier.py
# ------------------------------------------------------------
# ⚠️  STUB FILE — Owned by Person A (Backend Developer)
# Person B: DO NOT edit this file
# ------------------------------------------------------------

def start_notifier():
    """Starts the background expiry notification scheduler"""
    pass  # Person A will implement this